### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by danzipie** [dmpierre/sha1-circom#6]
Hello, would be great to have a license file (MIT according to package.json?) and distribute a npm package if possible. I found already one use https://github.com/rarimo/passport-zk-circuits/blob/main/passportVerification/utils/sha1.circom and would like to use as well.

**Comment by Divide-By-0** [comment]
You can use a MIT licensed audited RSA on NPM with https://www.npmjs.com/package/@zk-email/circuits as well!

**Comment by dmpierre** [comment]
Hey @danzipie thanks for suggesting, packaging it is a great idea. Let me come back to you on this!

**Comment by dmpierre** [comment]
License file added, opening an issue on packaging it.
